### PR TITLE
doc: adding first draft of the documentation site

### PR DESCRIPTION
**Pull request by spekulatius**
Hello @Kocal 

As discussed in #586, I've prepared a VuePress site in detail this contains:

- It lives in `docs/` and has it's own `package.json`.
- The development and production workflow from the wiki,
- The Vue Devtools solution as a separate page
- Rewording of a few sentences to make them work in the context and added a few more text blocks for it.
- Turning code-blocks into the right format for VuePress
- Turning Notes into VuePress note-blocks

This is a first draft and it can be updated/tweaked as you like. I'm keen to see if goes in the right direction for you. Let me know what you think :)

Thank you,
Peter

### CODE REVIEW

**Comment by spekulatius** [comment]
It looks like `yarn` isn't available in this build container?!

**Comment by Kocal** [comment]
Hi @spekulatius,

Wow! I am amazingly surprised! :astonished: 
This is really better than what I _expected_, thanks you for your work!

I will reword some sentences and merge your PR :slightly_smiling_face:

**Comment by Kocal** [comment]
Aaaaah, 8 years of GitHub and I still don't understand how to push on forks..... :sob: 

I will merge your PR and do some updates.

Again, a big thank you for your work! :slightly_smiling_face:

**Comment by spekulatius** [comment]
Hey @Kocal 

awesome, glad you like it! :)

I'll update a few more things over the next days and add knowledge in can find in the issues. Can you think of important things, which should be included?

Re: Pushing to a fork - I wouldn't know how to do it :D All good

Cheers,
Peter

**Comment by Kocal** [comment]
Hey :)

> Can you think of important things, which should be included?

Mmmmmh nope, I can't think of anything else :thinking:

**Comment by spekulatius** [comment]
Okay, that's fine @Kocal  :)

**Pull request merged**
