### PR TITLE
Vue CLI 3+ preset

### PR DESCRIPTION
**Pull request by Kocal**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| Tests pass?   | yes    
| Fixed tickets | #315 #616   

Following https://github.com/Kocal/vue-web-extension/issues/315#issuecomment-422479481

This Vue CLI 2 boilerplate become a Vue CLI 3+ preset :tada: 

Babel, ESLint, vue-router, vuex and axios can be installed/configured, and all the "web extension logic"  is now done by @adambullmer's [vue-cli-plugin-browser-extension](https://github.com/adambullmer/vue-cli-plugin-browser-extension).

Note that Mozilla's [web extension polyfill](https://github.com/mozilla/webextension-polyfill) is still used, and the automatic webextension reloading in browser is still present (`yarn serve`).

### CODE REVIEW

**Comment by spekulatius** [comment]
Hey @Kocal 

what a large change! Thanks for progressing the project!

Cheers,
Peter

**Comment by Kocal** [comment]
Hi Peter, thanks! :)

**Comment by quanengineering** [comment]
Wow, congratulations :D. This is what I always dream about.

**Comment by Kocal** [comment]
Thanks :)

**Comment by mp3il** [comment]
What an awesome job, @Kocal 

Cheers!

**Pull request merged**
